# Custom Language File for Launcher Customizer

[ejs.app]
title = "DreamzLauncher"

[ejs.landing]
mediaGitHubURL = "https://dreamzquest.wstr.fr"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/8bmSaqqz"

[ejs.settings]
sourceGithubLink = "https://github.com/scoogend/DreamzLauncher"
supportLink = "https://github.com/Scoogend/DreamzLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue dans Battle Of The Conquerors !"
welcomeDescription = "Plongez dans l'aventure palpitante de Battle of the Conquerors, un RPG faction immersif sur la sublime carte Drehmal: Apotheosis ! Explorez des villages, conquérez des territoires, affrontez des boss et immergez-vous dans l'univers fantastique de Battle of the Conquerors !"
welcomeDescCTA = "Vous n'êtes qu'à quelques clics d'une aventure inoubliable !"
